Donetsk empire = Донецька імперія
Palrament = Парламент
Child of Donbass = Дитя Донбасу
Children of the Mines = Діти шахт
Congratulations! = Вітаємо!
We are children of miners who want to rebuild Ukraine. = Ми діти шахтарів, які хочуть відновити Україну.
The Doetzian Empire came into fashion, which, due to the events of 2014, separated and began to exist independently, but despite Moscow's influence, people were essentially slaves, and on February 24, 2022, Moscow attacked and occupied independent Ukraine, and the world's reaction to this was sluggish, and because of this, people in Donbass begin to organize themselves and fight against the yoke of Moscow, (Note: the developer has never been to the Donetsk region, so please do not scold. = Донецька Імперія, через події 2014 року відокремилась і почала самостійне існування, але попри московський вплив люди були по суті рабами. 24 лютого 2022 року москва напала на незалежну Україну та окупувала її, а реакція світу була млявою. Через це люди Донбасу почали самоорганізовуватись і боротись проти московського ярма. (Примітка: розробник ніколи не був у Донецькій області, тому просимо не сварити.)
You are not worthy of war with me! = Нікчемо, ти не вартий війни зі мною!
Do you want to play? Then don't ask for mercy! = Хочеш пограти? Тоді не проси пощади!
What if? = А що як?
Do you have a skill? = Маєш хист?
Ew! = Фу!
What do you want? = Чого тобі треба?
We are listening to you = Ми вас слухаємо
Yes, please = Так, прошу
Are you stupid? I'm not going to do it! = Ти дурний? Я цього не зроблю!
Yeah, right = Ага, звісно
So wait, buddy! = Почекай, друже!
Okay! = Гаразд!
Okay, fine = Що ж, домовились
Speak! = Говори!
What do you say? = Що ти скажеш?
Next. = Далі.
Ahahaha, you made me laugh! = Ахаха, розсмішив мене!
No! Oh, what? = Ні! Та що ти!
Good = Добре
Hmm, that's not bad! = Хм, непогано!
That's not bad! = Непогано!
We had a lot of fun! = Добряче ми погрались!
or do you want to trade? = Чи не хочете поторгувати?

# Units
Donbas Miner = Донбаський шахтар

# Buildings / Improvements
Donbas Mine = Донбаська шахта
The earth gives us its strength. = Земля дає нам свою силу.

